# hugo version
[hugoVersion]
extended = true

# button
[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/buttons"
[[imports.mounts]]
source = "buttons/layouts/shortcodes"
target = "layouts/shortcodes"

# codepen
[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/codepen"
[[imports.mounts]]
source = "codepen/layouts/shortcodes"
target = "layouts/shortcodes"

# collapse
[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/collapse"
[[imports.mounts]]
source = "collapse/layouts/shortcodes"
target = "layouts/shortcodes"

# notice
[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/notice"
[[imports.mounts]]
source = "notice/layouts/shortcodes"
target = "layouts/shortcodes"
[[imports.mounts]]
source = "notice/assets/scss"
target = "assets/scss"

# video
[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/video"
[[imports.mounts]]
source = "video/layouts/shortcodes"
target = "layouts/shortcodes"

# tabs
[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/tabs"
[[imports.mounts]]
source = "tabs/layouts/shortcodes"
target = "layouts/shortcodes"
[[imports.mounts]]
source = "tabs/assets/scss"
target = "assets/scss"

# image
[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/image"
[[imports.mounts]]
source = "image/layouts/shortcodes"
target = "layouts/shortcodes"
[[imports.mounts]]
source = "image/assets/scss"
target = "assets/scss"

# gallery
[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/gallery"
[[imports.mounts]]
source = "gallery/layouts/shortcodes"
target = "layouts/shortcodes"
[[imports.mounts]]
source = "gallery/layouts/partials"
target = "layouts/partials"
[[imports.mounts]]
source = "gallery/assets/scss"
target = "assets/scss"
[[imports.mounts]]
source = "gallery/assets/plugins"
target = "assets/plugins"
